# An end-to-end scikit-learn workflow

In [25]:
import pandas as pd
import numpy as np

In [7]:
heart_disease = pd.read_csv('Heart_Disease_Prediction.csv')
heart_disease

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,Absence
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,Absence
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,Absence
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,Absence
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,Presence

In [3]:
heart_disease['Heart Disease'].map({'Presence': 0, 'Absence': 1})

0      0
1      1
2      0
3      1
4      1
      ..
265    1
266    1
267    1
268    1
269    0
Name: Heart Disease, Length: 270, dtype: int64

In [9]:
heart_disease['Heart Disease'] = heart_disease['Heart Disease'].map({'Presence': 0, 'Absence': 1})

In [10]:
heart_disease.head()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,0
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,1
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,0
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,1
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,1

In [11]:
heart_disease = heart_disease.rename(columns = {'Heart Disease': 'Target'})
heart_disease

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Target
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,0
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,1
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,0
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,1
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,1
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,1
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,1
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,1
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,0

In [12]:
#Create X(features matrix)
X = heart_disease.drop('Target', axis=1)

#create y (labels)
y = heart_disease['Target']

In [50]:
#to know version of sklearn
import sklearn
sklearn.show_versions()

C:\Users\admin\Desktop\sampleproj\env\lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

System:
    python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\admin\Desktop\sampleproj\env\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 21.2.4
   setuptools: 61.2.0
      sklearn: 1.0.2
        numpy: 1.22.3
        scipy: 1.7.3
       Cython: None
       pandas: 1.4.2
   matplotlib: 3.5.1
       joblib: 1.1.0
threadpoolctl: 2.2.0

Built with OpenMP: True

In [14]:
#using random forest classifier
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()  #clf->classifier

#clf = RandomForestClassifier(n-estimators = 100) it is 100 by default
#keep default hyperparameters    
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [19]:
#fit the model to data(splitting into training and test data)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [20]:
clf.fit(X_train,y_train)

RandomForestClassifier()

In [21]:
X_train

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
95,47,1,4,110,275,0,2,118,1,1.0,2,1,3
241,39,1,3,140,321,0,2,182,0,0.0,1,0,3
189,70,1,3,160,269,0,0,112,1,2.9,2,1,7
63,60,0,1,150,240,0,0,171,0,0.9,1,0,3
246,65,1,4,110,248,0,2,158,0,0.6,1,2,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,50,0,4,110,254,0,2,159,0,0.0,1,0,3
262,58,1,2,120,284,0,2,160,0,1.8,2,0,3
261,60,1,4,130,206,0,2,132,1,2.4,2,2,7
218,54,1,3,120,258,0,2,147,0,0.4,2,0,7
214,29,1,2,130,204,0,2,202,0,0.0,1,0,3

In [22]:
X_test

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
197,54,0,3,110,214,0,0,158,0,1.6,2,0,3
19,40,1,1,140,199,0,0,178,1,1.4,1,0,7
215,41,0,2,130,204,0,2,172,0,1.4,1,0,3
180,42,1,3,120,240,1,0,194,0,0.8,3,0,7
242,53,0,4,130,264,0,2,143,0,0.4,2,0,3
144,54,1,2,192,283,0,2,195,0,0.0,1,1,7
159,66,0,4,178,228,1,0,165,1,1.0,2,2,7
118,66,0,1,150,226,0,0,114,0,2.6,3,0,3
67,58,0,2,136,319,1,2,152,0,0.0,1,2,3
210,59,1,1,170,288,0,2,159,0,0.2,2,0,7
181,56,0,4,134,409,0,2,150,1,1.9,2,2,7
184,53,1,3,130,246,1,2,173,0,0.0,1,3,3
178,67,1,4,125,254,1,0,163,0,0.2,2,2,7
121,54,1,4,122,286,0,2,116,1,3.2,2,2,3
55,41,0,2,105,198,0,0,168,0,0.0,1,1,3
133,64,1,4,120,246,0,2,96,1,2.2,3,1,3
30,57,1,3,128,229,0,2,150,0,0.4,2,1,7
222,57,1,3,150,168,0,0,174,0,1.6,1,0,3
76,45,1,4,104,208,0,2,148,1,3.0,2,0,3
46,49,1,3,118,149,0,2,126,0,0.8,1,3,3
82,58,1,4,150,270,0,2,111,1,0.8,1,0,7
158,56,1,1,120,193,0,2,162,0,1.9,2,0,7
24,54,0,2,132,288,1,2,159,1,0.0,1,1,3
39,48,1,4,122,222,0,2,186,0,0.0,1,0,3
122,57,1,4,152,274,0,0,88,1,1.2,2,1,7
238,47,1,3,138,257,0,2,156,0,0.0,1,0,3
10,59,1,4,135,234,0,0,161,0,0.5,2,0,7
208,64,1,3,125,309,0,0,131,1,1.8,2,0,7
14,57,0,4,128,303,0,2,159,0,0.0,1,1,3
71,57,0,4,120,354,0,0,163,1,0.6,1,0,3
131,66,1,4,112,212,0,2,132,1,0.1,1,1,3
127,52,0,3,136,196,0,2,169,0,0.1,2,0,3
174,34,1,1,118,182,0,2,174,0,0.0,1,0,3
112,60,0,4,158,305,0,2,161,0,0.0,1,0,3
68,44,0,3,118,242,0,0,149,0,0.3,2,1,3
83,41,1,3,130,214,0,2,168,0,2.0,2,0,3
79,56,1,2,120,236,0,0,178,0,0.8,1,0,3
60,57,1,3,150,126,1,0,173,0,0.2,1,1,7
224,35,0,4,138,183,0,0,182,0,1.4,1,0,3
231,39,1,4,118,219,0,0,140,0,1.2,2,0,7
257,55,1,4,132,353,0,0,132,1,1.2,2,1,7
124,54,1,3,125,273,0,2,152,0,0.5,3,1,3
134,54,1,3,150,232,0,2,165,0,1.6,1,0,7
17,53,1,4,140,203,1,2,155,1,3.1,3,0,7
100,44,0,3,108,141,0,0,175,0,0.6,2,0,3
93,54,1,4,110,206,0,2,108,1,0.0,2,1,3
146,52,1,4,112,230,0,0,160,0,0.0,1,1,3
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7
92,54,1,4,124,266,0,2,109,1,2.2,2,1,7
106,51,1,3,100,222,0,0,143,1,1.2,2,0,3
120,49,1,3,120,188,0,0,139,0,2.0,2,3,7
154,51,0,3,130,256,0,2,149,0,0.5,1,0,3
107,60,0,4,150,258,0,2,157,0,2.6,2,2,7
47,44,1,4,110,197,0,2,177,0,0.0,1,1,3

In [23]:
y_train

95     0
241    1
189    0
63     1
246    0
      ..
166    1
262    0
261    0
218    1
214    1
Name: Target, Length: 216, dtype: int64

In [24]:
y_test

197    1
19     1
215    1
180    1
242    1
144    0
159    0
118    1
67     0
210    0
181    0
184    1
178    0
121    0
55     1
133    0
30     0
222    1
76     1
46     0
82     0
158    1
24     1
39     1
122    0
238    1
10     1
208    0
14     1
71     1
131    0
127    1
174    1
112    0
68     1
83     1
79     1
60     1
224    1
231    0
257    0
124    1
134    1
17     0
100    1
93     0
146    0
3      1
92     0
106    1
120    0
154    1
107    0
47     0
Name: Target, dtype: int64

In [28]:
y_label = clf.predict(np.array([1,2,3,4]))

C:\Users\admin\Desktop\sampleproj\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ValueError: Expected 2D array, got 1D array instead:
array=[1. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [29]:
#to make predictions 
y_pred = clf.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1], dtype=int64)

In [30]:
#evaluate the model on training data and test data
clf.score(X_train, y_train)

1.0

In [31]:
clf.score(X_test, y_test)

0.7962962962962963

Hence accuracy of 79%

In [32]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.71      0.76        24
           1       0.79      0.87      0.83        30

    accuracy                           0.80        54
   macro avg       0.80      0.79      0.79        54
weighted avg       0.80      0.80      0.79        54

In [34]:
print(confusion_matrix(y_test, y_pred))

[[17  7]
 [ 4 26]]

In [35]:
accuracy_score(y_test, y_pred)

0.7962962962962963

In [46]:
#to improve the model
#1. try different amts of n-estimators
np.random.seed(0)

for i in range(10, 110, 10):
    print(f"Trying model with {i} estimators")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set {clf.score(X_test, y_test) *100}")
    print("")

Trying model with 10 estimators
Model accuracy on test set 72.22222222222221

Trying model with 20 estimators
Model accuracy on test set 77.77777777777779

Trying model with 30 estimators
Model accuracy on test set 79.62962962962963

Trying model with 40 estimators
Model accuracy on test set 77.77777777777779

Trying model with 50 estimators
Model accuracy on test set 68.51851851851852

Trying model with 60 estimators
Model accuracy on test set 77.77777777777779

Trying model with 70 estimators
Model accuracy on test set 81.48148148148148

Trying model with 80 estimators
Model accuracy on test set 79.62962962962963

Trying model with 90 estimators
Model accuracy on test set 75.92592592592592

Trying model with 100 estimators
Model accuracy on test set 81.48148148148148

In [48]:
#save a model and load it
import pickle
pickle.dump(clf, open('random_forest1.pkl', "wb"))  #wb-> write binary

In [49]:
loaded_model = pickle.load(open("random_forest1.pkl", "rb"))  #rb-> read binary
loaded_model.score(X_test, y_test)

0.8148148148148148