# Classification Algorithms

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
heart_disease = pd.read_csv('Heart_Disease_Prediction.csv')

In [4]:
heart_disease.head(10)

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
5,65,1,4,120,177,0,0,140,0,0.4,1,0,7,Absence
6,56,1,3,130,256,1,2,142,1,0.6,2,1,6,Presence
7,59,1,4,110,239,0,2,142,1,1.2,2,1,7,Presence
8,60,1,4,140,293,0,2,170,0,1.2,2,2,7,Presence
9,63,0,4,150,407,0,2,154,0,4.0,2,3,7,Presence

In [5]:
heart_disease = heart_disease.rename(columns = {'Heart Disease': 'Target'})
heart_disease

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Target
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,Absence
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,Absence
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,Absence
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,Absence
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,Presence

In [6]:
heart_disease['Target'] = heart_disease['Target'].map({"Presence": 1, "Absence": 0})
heart_disease

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Target
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,1
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,0
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,1
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,0
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,0
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,0
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,0
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,0
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,1

## Linear SVC

In [7]:
#import
from sklearn.svm import LinearSVC

#Setup random seed
np.random.seed(0)

#create X and y
X = heart_disease.drop('Target', axis=1)
y = heart_disease['Target']

#Training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#create model
clf = LinearSVC()
clf.fit(X_train, y_train)

#testing data
clf.score(X_test, y_test)

C:\Users\admin\Desktop\sampleproj\env\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

0.7592592592592593

## Bernoulli's Naive Bayes

In [8]:
from sklearn.naive_bayes import BernoulliNB

#generate random seed
np.random.seed(0)

#X and y
X = heart_disease.drop('Target', axis=1)
y = heart_disease['Target']

#training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#create model
clf = BernoulliNB()
clf.fit(X_train, y_train)

#score
clf.score(X_test, y_test)

0.7222222222222222

## Random Forest Classifier

In [10]:
from sklearn.ensemble import RandomForestClassifier

#generate random seed
np.random.seed(0)

#X and y
X = heart_disease.drop('Target', axis=1)
y = heart_disease['Target']

#training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#model
clf = RandomForestClassifier()
clf.fit(X_train, y_train)

#score
clf.score(X_test, y_test)

0.7962962962962963

## KNeighbors

In [12]:
from sklearn.neighbors import KNeighborsClassifier

np.random.seed(0)

X = heart_disease.drop('Target', axis=1)
y = heart_disease['Target']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

clf = KNeighborsClassifier()
clf.fit(X_train, y_train)

clf.score(X_test, y_test)

0.7037037037037037

If you have structured data use ensemble methods
If you have unstructure data use deep learning or transfer learning